### ISSUE TITLE
AttributeError: 'ScatterableList' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by jaeyun95** [rowanz/r2c#14]
i have a problem like this:
Traceback (most recent call last):
  File "eval_for_leaderboard.py", line 110, in <module>
    batch = _to_gpu(batch)
  File "eval_for_leaderboard.py", line 74, in _to_gpu
    td[k] = {k2: v.cuda(async=True) for k2, v in td[k].items()} if isinstance(td[k], dict) else td[k].cuda(
AttributeError: 'ScatterableList' object has no attribute 'cuda'

what can i do? 

thank you:)

**Comment by rowanz** [comment]
sorry for the delay -- are you trying with 3 GPUs or just 1?

**Comment by jaeyun95** [comment]
> sorry for the delay -- are you trying with 3 GPUs or just 1?

just 1 GPU!!

**Comment by Zzmonica** [comment]
Excuse me, have you solved this problem? I ran into the same one.

**Comment by woosikyang** [comment]
안녕하세요 한국인이신거같아서 여쭤보는데 저도 gpu1개라 같은 에러가 나는데 혹시 해결 하셨나요??

**Comment by jaeyun95** [comment]
아니요! 저 때 해결 못하고 eval_q2ar.py로만 성능평가했습니다!

**Comment by woosikyang** [comment]
코드 까보니까 딕셔너리 키중에 metadata문제더라구요 train.py 보시면 metadata일경우 cuda 변화 안시키게 _to_gpu함수 변경한거 있으니 그거로 바꿔서 다시 돌리시면 돌아갈겁니다!

**Comment by yekeren** [comment]
I got the same error but found "export CUDA_VISIBLE_DEVICES=0,1,2" is the solution. So, the code assumes we use 3 GPUs.

**Comment by arjunsinghrana** [comment]
Hi I am getting the same error right now and it is not being fixed by the above mentioned solutions. 
I am using 1 GPU for this. 

Any help?
